// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"models/ent/predicate"
	"models/ent/transference"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransferenceDelete is the builder for deleting a Transference entity.
type TransferenceDelete struct {
	config
	hooks    []Hook
	mutation *TransferenceMutation
}

// Where appends a list predicates to the TransferenceDelete builder.
func (td *TransferenceDelete) Where(ps ...predicate.Transference) *TransferenceDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TransferenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, TransferenceMutation](ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TransferenceDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TransferenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(transference.Table, sqlgraph.NewFieldSpec(transference.FieldID, field.TypeUUID))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TransferenceDeleteOne is the builder for deleting a single Transference entity.
type TransferenceDeleteOne struct {
	td *TransferenceDelete
}

// Where appends a list predicates to the TransferenceDelete builder.
func (tdo *TransferenceDeleteOne) Where(ps ...predicate.Transference) *TransferenceDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *TransferenceDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{transference.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TransferenceDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
