// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"models/ent/predicate"
	"models/ent/transference"
	"models/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TransferenceQuery is the builder for querying Transference entities.
type TransferenceQuery struct {
	config
	ctx          *QueryContext
	order        []OrderFunc
	inters       []Interceptor
	predicates   []predicate.Transference
	withFromUser *UserQuery
	withToUser   *UserQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TransferenceQuery builder.
func (tq *TransferenceQuery) Where(ps ...predicate.Transference) *TransferenceQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TransferenceQuery) Limit(limit int) *TransferenceQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TransferenceQuery) Offset(offset int) *TransferenceQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TransferenceQuery) Unique(unique bool) *TransferenceQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TransferenceQuery) Order(o ...OrderFunc) *TransferenceQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryFromUser chains the current query on the "from_user" edge.
func (tq *TransferenceQuery) QueryFromUser() *UserQuery {
	query := (&UserClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transference.Table, transference.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, transference.FromUserTable, transference.FromUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryToUser chains the current query on the "to_user" edge.
func (tq *TransferenceQuery) QueryToUser() *UserQuery {
	query := (&UserClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transference.Table, transference.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, transference.ToUserTable, transference.ToUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Transference entity from the query.
// Returns a *NotFoundError when no Transference was found.
func (tq *TransferenceQuery) First(ctx context.Context) (*Transference, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{transference.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TransferenceQuery) FirstX(ctx context.Context) *Transference {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Transference ID from the query.
// Returns a *NotFoundError when no Transference ID was found.
func (tq *TransferenceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{transference.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TransferenceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Transference entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Transference entity is found.
// Returns a *NotFoundError when no Transference entities are found.
func (tq *TransferenceQuery) Only(ctx context.Context) (*Transference, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{transference.Label}
	default:
		return nil, &NotSingularError{transference.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TransferenceQuery) OnlyX(ctx context.Context) *Transference {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Transference ID in the query.
// Returns a *NotSingularError when more than one Transference ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TransferenceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{transference.Label}
	default:
		err = &NotSingularError{transference.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TransferenceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Transferences.
func (tq *TransferenceQuery) All(ctx context.Context) ([]*Transference, error) {
	ctx = setContextOp(ctx, tq.ctx, "All")
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Transference, *TransferenceQuery]()
	return withInterceptors[[]*Transference](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TransferenceQuery) AllX(ctx context.Context) []*Transference {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Transference IDs.
func (tq *TransferenceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, "IDs")
	if err = tq.Select(transference.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TransferenceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TransferenceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, "Count")
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TransferenceQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TransferenceQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TransferenceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, "Exist")
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TransferenceQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TransferenceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TransferenceQuery) Clone() *TransferenceQuery {
	if tq == nil {
		return nil
	}
	return &TransferenceQuery{
		config:       tq.config,
		ctx:          tq.ctx.Clone(),
		order:        append([]OrderFunc{}, tq.order...),
		inters:       append([]Interceptor{}, tq.inters...),
		predicates:   append([]predicate.Transference{}, tq.predicates...),
		withFromUser: tq.withFromUser.Clone(),
		withToUser:   tq.withToUser.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithFromUser tells the query-builder to eager-load the nodes that are connected to
// the "from_user" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TransferenceQuery) WithFromUser(opts ...func(*UserQuery)) *TransferenceQuery {
	query := (&UserClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withFromUser = query
	return tq
}

// WithToUser tells the query-builder to eager-load the nodes that are connected to
// the "to_user" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TransferenceQuery) WithToUser(opts ...func(*UserQuery)) *TransferenceQuery {
	query := (&UserClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withToUser = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Amount float64 `json:"amount,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Transference.Query().
//		GroupBy(transference.FieldAmount).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TransferenceQuery) GroupBy(field string, fields ...string) *TransferenceGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TransferenceGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = transference.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Amount float64 `json:"amount,omitempty"`
//	}
//
//	client.Transference.Query().
//		Select(transference.FieldAmount).
//		Scan(ctx, &v)
func (tq *TransferenceQuery) Select(fields ...string) *TransferenceSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TransferenceSelect{TransferenceQuery: tq}
	sbuild.label = transference.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TransferenceSelect configured with the given aggregations.
func (tq *TransferenceQuery) Aggregate(fns ...AggregateFunc) *TransferenceSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TransferenceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !transference.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TransferenceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Transference, error) {
	var (
		nodes       = []*Transference{}
		withFKs     = tq.withFKs
		_spec       = tq.querySpec()
		loadedTypes = [2]bool{
			tq.withFromUser != nil,
			tq.withToUser != nil,
		}
	)
	if tq.withFromUser != nil || tq.withToUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, transference.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Transference).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Transference{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withFromUser; query != nil {
		if err := tq.loadFromUser(ctx, query, nodes, nil,
			func(n *Transference, e *User) { n.Edges.FromUser = e }); err != nil {
			return nil, err
		}
	}
	if query := tq.withToUser; query != nil {
		if err := tq.loadToUser(ctx, query, nodes, nil,
			func(n *Transference, e *User) { n.Edges.ToUser = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TransferenceQuery) loadFromUser(ctx context.Context, query *UserQuery, nodes []*Transference, init func(*Transference), assign func(*Transference, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Transference)
	for i := range nodes {
		if nodes[i].user_from_transfers == nil {
			continue
		}
		fk := *nodes[i].user_from_transfers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_from_transfers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tq *TransferenceQuery) loadToUser(ctx context.Context, query *UserQuery, nodes []*Transference, init func(*Transference), assign func(*Transference, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Transference)
	for i := range nodes {
		if nodes[i].user_to_transfers == nil {
			continue
		}
		fk := *nodes[i].user_to_transfers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_to_transfers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tq *TransferenceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TransferenceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(transference.Table, transference.Columns, sqlgraph.NewFieldSpec(transference.FieldID, field.TypeUUID))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transference.FieldID)
		for i := range fields {
			if fields[i] != transference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TransferenceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(transference.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = transference.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TransferenceGroupBy is the group-by builder for Transference entities.
type TransferenceGroupBy struct {
	selector
	build *TransferenceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TransferenceGroupBy) Aggregate(fns ...AggregateFunc) *TransferenceGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TransferenceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, "GroupBy")
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransferenceQuery, *TransferenceGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TransferenceGroupBy) sqlScan(ctx context.Context, root *TransferenceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TransferenceSelect is the builder for selecting fields of Transference entities.
type TransferenceSelect struct {
	*TransferenceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TransferenceSelect) Aggregate(fns ...AggregateFunc) *TransferenceSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TransferenceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, "Select")
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransferenceQuery, *TransferenceSelect](ctx, ts.TransferenceQuery, ts, ts.inters, v)
}

func (ts *TransferenceSelect) sqlScan(ctx context.Context, root *TransferenceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
